Repository tkl-labs/chat, pull requests merged in 2025-05, with the labels that each got.

#5 Added Login + Register Pages with Notification Context
  package-lock.json
  package.json
  src/app/components/auth-form.tsx
  src/app/components/notification-provider.tsx
  src/app/components/notification.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/register/page.tsx
  src/lib/notification-store.ts
Labels: enhancement

#6 feat: Add cargo fmt ci/cd pipeline
  .github/cargo-fmt.yml
Labels: enhancement

#13 Add auth frontend
  next.config.ts
  package-lock.json
  package.json
  src-tauri/tauri.conf.json
  src/app/chat/[groupId]/layout.tsx
  src/app/chat/[groupId]/page.tsx
  src/app/components/auth-form.tsx
  src/app/components/chat-message.tsx
  src/app/components/chat-sidebar.tsx
  src/app/components/notification.tsx
  src/app/components/skeletons.tsx
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/not-found.tsx
  src/app/page.tsx
  src/app/profile/layout.tsx
  src/app/profile/page.tsx
  src/lib/axios.ts
  src/lib/db-types.ts
  src/lib/mock-data.ts
Labels: enhancement

#14 Fix CORS and status codes
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/actix/auth/login.rs
  backend/src/actix/auth/register.rs
  backend/src/actix/start.rs
  backend/src/schema.rs
  next.config.ts
  src-tauri/tauri.conf.json
  src/app/components/auth-form.tsx
  src/lib/axios.ts
Labels: bugfix

#15 Split frontend and core of application
  .env.example
  .github/dependabot.yml
  .github/workflows/cargo-fmt.yml
  .gitignore
  README.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/diesel.toml
  backend/migrations/.keep
  backend/migrations/00000000000000_diesel_initial_setup/down.sql
  backend/migrations/00000000000000_diesel_initial_setup/up.sql
  backend/migrations/2025-05-21-103036_create_users/down.sql
  backend/migrations/2025-05-21-103036_create_users/up.sql
  backend/migrations/2025-05-21-103113_create_groups/down.sql
  backend/migrations/2025-05-21-103113_create_groups/up.sql
  backend/migrations/2025-05-21-103118_create_group_members/down.sql
  backend/migrations/2025-05-21-103118_create_group_members/up.sql
  backend/src/actix/auth/login.rs
  backend/src/actix/auth/mod.rs
  backend/src/actix/auth/register.rs
  backend/src/actix/mod.rs
  backend/src/actix/routes.rs
  backend/src/actix/start.rs
  backend/src/database/init.rs
  backend/src/database/mod.rs
  backend/src/lib.rs
  backend/src/main.rs
  backend/src/models.rs
  backend/src/schema.rs
  backend/src/server.rs
  compose.yaml
  package-lock.json
  schema/mongo/init.js
  schema/postgres/init.sql
  src/app/components/chat-message.tsx
  src/app/components/chat-sidebar.tsx
Labels: documentation, enhancement, dependencies
